GET {{Restaurants_API_HostAddress}}/api/restaurants

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "New Restaurant with logs",
  "category": "Italian",
  "description": "A new restaurant description",
  "hasDelivery": true,
  "contactEmail": "politecoder97@gmail.com",
  "contactPhone": "123-456-7890",
  "city": "New City",
  "street": "123 New Street",
  "postalCode": "12-345"
}

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/1

###

PATCH {{Restaurants_API_HostAddress}}/api/restaurants/1006
Content-Type: application/json

{
  "name": "Update New Restaurant",
  "category": "Mexican",
  "description": "A new updated restaurant description",
  "hasDelivery": true,
  "contactEmail": "politecoder97@gmail.com",
  "contactPhone": "123-456-7890",
  "city": "New City",
  "street": "123 New Street",
  "postalCode": "12-345"
}